alias: Alarm Disarmed
description: ""
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel.alarmo
    to: disarmed
condition: []
action:
  - service: media_player.media_stop
    data: {}
    target:
      entity_id:
        - media_player.computerrm_sonos
        - media_player.kitchen_sonos
        - media_player.move_sonos
        - media_player.livingroom_sonos
  - service: media_player.volume_set
    data:
      volume_level: 0.08
    target:
      entity_id:
        - media_player.computerrm_sonos
        - media_player.kitchen_sonos
        - media_player.move_sonos
        - media_player.livingroom_sonos
mode: single
