blueprint:
  name: Xfinity Keypad Alarmo Sync ver 1.1
  description: Xfinity Keypad sync with Alarmo ver 1.1
  domain: automation

  input:
    keypad1_topic:
      name: Keypad 1 MQTT Topic
      description: "The Topic is composed of your Zigbee2MQTT base_topic (see your Z2M Addon Configuration) and the Friendly Name of your keypad in Z2M. Example: zigbee2mqtt/Keypad"
      selector:
        text:
    keypad2_topic:
      name: Keypad 2 MQTT Topic
      description: "The Topic is composed of your Zigbee2MQTT base_topic (see your Z2M Addon Configuration) and the Friendly Name of your keypad in Z2M. Example: zigbee2mqtt/Keypad"
      selector:
        text:
    keypad3_topic:
      name: Keypad 3 MQTT Topic
      description: "The Topic is composed of your Zigbee2MQTT base_topic (see your Z2M Addon Configuration) and the Friendly Name of your keypad in Z2M. Example: zigbee2mqtt/Keypad"
      selector:
        text:
    entity:
      name: Alarmo entity
      description: "An alarm control panel entity from alarmo."
      selector:
        entity:
          domain: alarm_control_panel
          integration: alarmo

trigger:
  - platform: mqtt
    topic: !input keypad1_topic
    id: keypad1_triggered
  - platform: mqtt
    topic: !input keypad2_topic
    id: keypad2_triggered
  - platform: mqtt
    topic: !input keypad3_topic
    id: keypad3_triggered

condition:
  - condition: or
    conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.action == "arm_day_zones"  }}'
      - condition: template
        value_template: '{{ trigger.payload_json.action == "disarm"  }}'
      - condition: template
        value_template: '{{ trigger.payload_json.action == "arm_night_zones"  }}'
      - condition: template
        value_template: '{{ trigger.payload_json.action == "arm_all_zones"  }}'

action:
  - service: persistent_notification.create
    data:
      message: >-
        action:{{ trigger.payload_json.action  }} code:{{
        trigger.payload_json.action_code  }}
    enabled: false
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: keypad1_triggered
              - condition: trigger
                id: keypad2_triggered
               - condition: trigger
                id: keypad3_triggered
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.payload_json.action == "arm_day_zones"  }}'
                    alias: Template condition arm_day_zones
                sequence:
                  - service: persistent_notification.create
                    data:
                      message: arm_day_zones
                    enabled: false
                  - service: alarmo.arm
                    data:
                      entity_id: !input entity
                      code: "{{ trigger.payload_json.action_code }}"
                      mode: away
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.payload_json.action == "arm_all_zones"  }}'
                    alias: template condition arm_all_zones
                sequence:
                  - service: persistent_notification.create
                    data:
                      message: arm all zones
                    enabled: false
                  - service: alarmo.arm
                    data:
                      entity_id: !input entity
                      code: "{{ trigger.payload_json.action_code }}"
                      mode: away
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.payload_json.action == "arm_night_zones"  }}'
                    alias: template condition arm =_night_zones
                sequence:
                  - service: persistent_notification.create
                    data:
                      message: arm night zones
                    enabled: false
                  - service: alarmo.arm
                    data:
                      entity_id: !input entity
                      code: "{{ trigger.payload_json.action_code }}"
                      mode: night
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.payload_json.action == "disarm"  }}'
                    alias: template condition disarm
                sequence:
                  - service: persistent_notification.create
                    data:
                      message: disarm
                    enabled: false
                  - service: alarmo.disarm
                    data:
                      entity_id: !input entity
                      code: "{{ trigger.payload_json.action_code }}"
mode: parallel
max: 10
