blueprint:
  name: Tag Arm and Disarm alarm-night
  description: Tag Arm and Disarm alarm-night
  domain: automation

  input:
    tag1:
      name: Tag Id that triggers the Arm/Disarm action
      description: "Tag Id that triggers the Arm/Disarm action"
      selector:
        text:
    tag2:
      name: Tag Id that triggers the Arm/Disarm action
      description: "Tag Id that triggers the Arm/Disarm action"
      selector:
        text:
    tag3:
      name: Tag Id that triggers the Arm/Disarm action
      description: "Tag Id that triggers the Arm/Disarm action"
      selector:
        text:
    tag4:
      name: Tag Id that triggers the Arm/Disarm action
      description: "Tag Id that triggers the Arm/Disarm action"
      selector:
        text:
    event_type1:
      name: Event Type that triggers the Arm/Disarm action
      description: "Event Type that triggers the Arm/Disarm action"
      selector:
        text:
    arm_mode:
      name: Arm Mode
      description: "Arm Mode"
      selector:
        select:
          options:
            - "arm_all_zones"
            - "arm_day_zones"
            - "arm_night_zones"
    code:
      name: Alarm code
      description: "Alarm code"
      selector:
        text:
    state_topic:
      name: MQTT State Topic of your Zigbee2MQTT Keypad
      description: "The State Topic is composed of your Zigbee2MQTT base_topic (see your Z2M Addon Configuration) and the Friendly Name of your keypad in Z2M. Example: zigbee2mqtt/Keypad"
      selector:
        text:
    set_topic:
      name: MQTT Set Topic of your Zigbee2MQTT Keypad
      description: "This is the same as your State Topic, with the addition of /set. Example: zigbee2mqtt/Keypad/set"
      selector:
        text:
    entity:
      name: Alarmo entity
      description: "An alarm control panel entity from alarmo."
      selector:
        entity:
          domain: alarm_control_panel
          integration: alarmo
variables:
  arm_mode_var: !input "arm_mode"

trigger:
  - platform: tag
    tag_id: !input tag1
  - platform: tag
    tag_id: !input tag2
  - platform: tag
    tag_id: !input tag3
  - platform: tag
    tag_id: !input tag4
  - platform: event
    event_type: !input event_type1
condition: []
action:
  - if:
      - condition: state
        entity_id: !input entity
        state: disarmed
    then:
      - service: alarmo.arm
        data:
          entity_id: !input entity
          code: !input code
          mode: night
      - service: mqtt.publish
        data:
          topic: !input set_topic
          payload_template: '{"arm_mode": {"mode": "{{ arm_mode_var }}"}}'
    else:
      - service: alarmo.disarm
        data:
          entity_id: !input entity
          code: !input code
      - service: mqtt.publish
        data:
          topic: !input set_topic
          payload: "\"{  \\\"arm_mode\\\":  { \\\"mode\\\": \\\"disarm\\\" }}\""
mode: restart
