alias: "Tag: Arm and Disarm alarm"
description: ""
trigger:
  - platform: tag
    tag_id: 11-54-E3-26
  - platform: event
    event_type: alarmo-phone-tap
  - platform: tag
    tag_id: Security-tag-1
    alias: When security-tag-1 is scanned
  - platform: tag
    tag_id: Security-tag-2
    alias: When security-tag-2 is scanned
  - platform: tag
    tag_id: Security-tag-3
    alias: When security-tag-3 is scanned
condition: []
action:
  - if:
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: disarmed
    then:
      - service: alarm_control_panel.alarm_arm_away
        data: {}
        target:
          entity_id: alarm_control_panel.alarmo
    else:
      - service: alarm_control_panel.alarm_disarm
        data: {}
        target:
          entity_id: alarm_control_panel.alarmo
mode: restart
