alias: Alarm Disarmed
description: ""
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel.alarmo
    to: disarmed
condition: []
action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
        - switch.smart_plug_6_socket
        - switch.smart_plug_5_socket
mode: single
