alias: "Tag: Arm and Disarm alarm-night"
description: ""
trigger:
  - platform: tag
    tag_id: 27cac199-a00d-4d31-90e3-7996ebcad731
condition: []
action:
  - if:
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: disarmed
    then:
      - service: alarm_control_panel.alarm_arm_night
        data:
          code: "5964"
        target:
          entity_id: alarm_control_panel.alarmo
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/Front_Door_Keypad/set
          payload: "\"{\\\"arm_mode\\\": { \\\"mode\\\": \\\"arm_night_zones\\\"}}\""
    else:
      - service: alarm_control_panel.alarm_disarm
        data:
          code: "5964"
        target:
          entity_id: alarm_control_panel.alarmo
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/Front_Door_Keypad/set
          payload: "\"{  \\\"arm_mode\\\":  { \\\"mode\\\": \\\"disarm\\\" }}\""
mode: restart
