esphome:
  name: greenbagel

esp8266:
  board: d1_mini
  framework:
    version: 2.7.4

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "qxCwml53B+89JNm6LwZfgEAJa8UvFFw4+cc9hbtAGVA="

ota:
  password: "e1957d45967a6bf660c5aa562627d11a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Buillyty Fallback Hotspot"
    password: "vMjksn7D2PgJ"

captive_portal:

light:
  #- platform: neopixelbus
  #  type: RGB
  #  variant: WS2812X
  #  pin: D5
  #  num_leds: 1
  #  name: "NeoPixel Light"
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D8
    num_leds: 1
    id: led_on_d4
    rgb_order: GRB
    name: "FastLED on D4"
  - platform: neopixelbus
    variant: WS2812
    pin: D4
    num_leds: 1
    flash_transition_length: 500ms
    type: GRB
    id: activity_led2
    name: "neopixelbus LED on D4"
    restore_mode: ALWAYS_OFF
